### ISSUE TITLE
Search with "@" in the URL

### ISSUE THREAD

**Issue by jochumdev** [GoyaPtyLtd/RESTfm#12]
I've tried to search for an E-Mail Address in RESTfm:

http://my-internal-restfm.lan/RESTfm/restfm_example/layout/us500/.json?RFMmax=1&RFMsF1=email&RFMsV1=vinouye%40aol.com

This fails with 401 - No records match the request.

While this works:

http://my-internal-restfm.lan/RESTfm/restfm_example/layout/us500/.html?RFMmax=1&RFMsF1=email&RFMsV1=vinouye*

Thanks for looking into this.

Rene

**Comment by nickorr** [comment]
Rene,

This isn't the place for support, it's for technical issues with the PHP code.

But @ and . are special symbols in a FileMaker find, so you need to escape them.  Easiest way to see this is to right click on a field in an existing system that has an email address in it, and do find matching.  Then do a Modify Last Find.  You end up with \ before the @ and . so that's what you'd need to do in your criteria too.

For more support please go here : http://restfm.com/purchase

Thanks,
Nick

**Comment by jochumdev** [comment]
Thanks, it wasn't clear for me that this is no technical issue but a usage issue.

I'll switch from https://github.com/mariaebene/py-restfmclient to a rewrite version of https://github.com/massmutual/py4jdbc - rewrite for async/await in python.
