### ISSUE TITLE
operation log remained

### ISSUE THREAD

**Issue by nikukyugamer** [GoyaPtyLtd/RESTfm#13]
GET method aside, POST, PUT and DELETE method make critical operation result occasionally.
So to rollback for example, I wish **logger function** is implemented, which is able to selected in config file.

I'm happy if you consider this somtimes ;-)

**Comment by gav-** [comment]
Outside of debugging, RESTfm already uses PHP's error logging facility for critical errors (which are usually sent to syslog or the windows event logger). This conveniently alleviates RESTfm from log file management and performance issues.

How much data would you want to log ? (The entire request and response, or just some meta data?)

**Comment by nikukyugamer** [comment]
@gav-  
hi gav-, sorry for very^n late response, sincerely 😓 

btw I'd like to want former, the entire request and response.
if possible, I'd love to!

sincerely

**Comment by gav-** [comment]
That could be a lot of data to write out over time, we would need to come up with some way to format it logically too.

It is already possible to dump the parsed request data, and the raw request and response, for debugging purposes, by setting 'dumpData' to TRUE in RESTfm.ini.php. I say 'debugging purposes' here because it will create a unique subdirectory for every HTTP transaction, which wouldn't be viable in a production environment.

**Comment by nikukyugamer** [comment]
@gav- 
I see very well, thank you.
if needed, my purpose will achieve by `dumpData` to `TRUE`.
thanks for explain detail!

to sexy product, `RESTfm` :)
