### ISSUE TITLE
RESTfm Returns 500 Error Whne No Records Found

### ISSUE THREAD

**Issue by billtucker** [GoyaPtyLtd/RESTfm#7]
I am running RESTfm version 4 on a IIS server and for the most part this version is great. I have one in to one issue and I am difficulty in understanding the behavior. I am search FM 15 for a possible set of records that match my search criteria with an understanding that in some cases no records will be found. The issue at hand is that RESTfm is returning a 500 Error over a 401 Error. The 500 error is where I see the issue as I would expect a simple JSON block with info status set to 401 which I can gracefully parse and process. The 500 error is not something I can ignore as it could be a more serious error. If you could help me understand why the application is returning a 500 error over a simple 401 it would be appreciated. I forgot to add if I am searching records were records are found everything works as advertised.

**Comment by gav-** [comment]
I will assume that you mean 404 (Not Found) in place of 401 (Unauthorized) in your comment.

The difficulty here is how to map a search-like function onto a REST-like URL and return an intelligible error code when the URL is correct, but the search returned no results.

A HTTP 404 code cannot be returned in your case as the URL is actually valid. In the case of a URL in the form of http://{server}/RESTfm/{database}/layout/{layout}/{recordId} with a non-existent {recordId} then the result will be HTTP 404.

So returning HTTP 500 and passing the FileMaker response code through as X-RESTfm-FM-Status (in both the HTTP header and in whichever output format you are using) is by design.

**Comment by marioantonini** [comment]
Just found [this question](http://stackoverflow.com/questions/11746894/what-is-the-proper-rest-response-code-for-a-valid-request-but-an-empty-data) in SO and was thinking that 204 might be appropriate.

**Comment by gav-** [comment]
At one point RESTfm used 204 in response to DELETE operations, but in trying to support rather limited HTTP clients (like FileMaker itself) that could not differentiate the 2xx return codes, we standardised on 200 for all successful operations.

FileMaker "find" can return many different error responses, only "No records match the request" could possibly map to HTTP 204. Client code must already expect HTTP 500 from RESTfm as an indicator to inspect X-RESTfm-FM-Status for details of the other cases, so there isn't any additional overhead in detecting the simple case for not matching any records (client side).

Thanks for your suggestion, even though we are unlikely to be breaking RESTfm's behaviour now that it's established, it is always worth revisiting some of these points.
